<a href="https://colab.research.google.com/github/Coder1010ayush/MachineLearning/blob/main/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
print(torch.__version__)
print(np.__version__)

2.0.1+cu118
1.23.5


In [7]:
# Creating an array in numpy
scalar = np.array(3) # scalar value
vector = np.array([1,2,3,4,5]) # one dimensional array
matrix = np.array([[1,2,3],
                    [4,5,6],
                   [7,8,9]])  # two dimensional array
print(scalar)
print(vector)
print(matrix)
# Dimension of the np array
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)

3
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
0
1
2


In [14]:
tensor = np.array([
    [
        [1,2],
        [3,4]
    ],[
        [6,7],
        [8,9]
    ]
])
print(tensor)
print(tensor.ndim)  # dimension of the array
print(tensor.shape) # it returns dimension of at each index
print(tensor.size)  # returns number of all elements in the array

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
3
(2, 2, 2)
8


### Data Types in numpy
There are many data types in the numpy such as :

            01 integer - 'i'
            02 string - 'S'
            03 boolean - 'b'
            04 float - 'f'
            05 complex data type - 'c'
            06 unsigned int - 'u'
            07 Object - 'O'
            08 timedelta - 'm'
            09 datetime - 'M'
            10 void - 'V'

In [17]:
arr = np.array(["apple","pineapple","orange"])
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([True,False,True,True])
arr_3 = np.array([1.2,3.5,6.8,9.0])
print(arr.dtype)
print(arr_1.dtype)
print(arr_2.dtype)
print(arr_3.dtype)

<U9
int64
bool
float64


In [19]:
# Converting one dtype to another
arr = np.array([1,2,3,4,5])
newarr = arr.astype('f') # astype is a method to convert one dtype to another dtype
print(arr)
print(newarr)

bool_arr = np.array([True,False,False,True])
str_arr = bool_arr.astype('S')
print(bool_arr)
print(str_arr)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True False False  True]
[b'True' b'False' b'False' b'True']


In [21]:
# Another way to change dtye of numpy arr
arr = np.array([1,2,3,4,5])
str_arr = np.array([2,3,4],dtype="S")
print(str_arr)
print(arr)

[b'2' b'3' b'4']
[1 2 3 4 5]


**Copy and View in numpy**
      Copy : it returns a new array which is similar as original array.  
              View : it returns a view or instance of original array it shares same memory space

In [22]:
tensor = np.array([1,2,3,4])
arr = np.array([5,6,7,8])
# Copy of the tensor
copy_tensor = tensor.copy()
# view of arr
view_arr = arr.view()

print(copy_tensor)
print(view_arr)

[1 2 3 4]
[5 6 7 8]


 base property return none in the case of copy and array in the case of view

In [23]:
# checking difference between copy and view
tensor = np.array([1,2,3,4,5])
copy = tensor.copy()
view = tensor.view()
print(copy.base)
print(view.base)

None
[1 2 3 4 5]
