<a href="https://colab.research.google.com/github/Coder1010ayush/MachineLearning/blob/main/numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###  Topics to be covered
        01. Array slicing
        02. Array indexing
        03. Array join
        04. Array split
        05. Array iterating
        06. Array Searching Sorting Filter
        07. Array reshaping

In [ ]:
import numpy as np

# Array indexing
tensor = np.array([1,2,3,4,5])
arr = np.array([[1,2],[3,4],[4,5]])
print(tensor,"Shape is ",tensor.shape,tensor.ndim)
print(arr,"Shape is ",arr.shape,arr.ndim)

print(tensor[0])
print(arr[0])
print(arr[1])


[1 2 3 4 5] Shape is  (5,) 1
[[1 2]
 [3 4]
 [4 5]] Shape is  (3, 2) 2
1
[1 2]
[3 4]


In [ ]:
matrix = np.array([10,20,30,40,50])
mat = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
]])
print(mat)
print("Shape is : ",mat.shape)
print("Dimension is : ",mat.ndim)
print(mat[0])
print(mat[1])
print(mat[0][0][2])
print(mat[: : 1])
print(mat[: 2 :])

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]
Shape is :  (2, 3, 4)
Dimension is :  3
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
3
[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]
[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]


In [ ]:
one = np.ones(5)
zero = np.zeros(10)
print(one)
one_1 = one.astype('i')
print(one.dtype)
print(zero)
print(zero.dtype)
print(one_1.dtype)

[1. 1. 1. 1. 1.]
float64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
int32


In [ ]:
# Arrays slicing
arr = np.array([1,2,3,4,5])
narr = arr[2 :]
narr1 = arr[: 3]
print(narr)
print(narr1)
print(narr.ndim,narr1.ndim)

[3 4 5]
[1 2 3]
1 1


In [ ]:
matr = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],[
                      [10,20,30],
                      [40,50,60],
                      [70,80,90]
                  ]])
print(matr)
print(matr.ndim)
newarr = matr[1, 2 :]
print(newarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
3
[[70 80 90]]
