<a href="https://colab.research.google.com/github/Coder1010ayush/MachineLearning/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
# Practice to tensor and manipulation
import torch
tensor = torch.arange(0,10)
tensor_1 = torch.tensor([[[2,3],
                         [4,5]],[[6,7],
                                 [8,9]]])
print(tensor_1[0]) #[[2,3],[4,5]]
print(tensor_1[1]) #[[6,7],[8,9]]
print(tensor_1[0][0]) #[2,3]
print(tensor_1[0][1]) #[4,5]

tensor([[2, 3],
        [4, 5]])
tensor([[6, 7],
        [8, 9]])
tensor([2, 3])
tensor([4, 5])


In [4]:
tensor_2 = torch.tensor([[[1,2,3],
                          [4,5,6],
                          [7,8,9]],[[10,20,30],
                                    [40,50,60],
                                    [70,80,90]],
                          [[100,200,300],
                         [500,600,700],
                         [400,800,900]]
                       ])
print(tensor_2.shape)
print(tensor_2[0])
print(tensor_2[0][1])
print(tensor_2[0][0][2])
print(tensor_2[2][2][1])
print(tensor_2[:,:,1])
print(tensor_2[:,1,:])

torch.Size([3, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([4, 5, 6])
tensor(3)
tensor(800)
tensor([[  2,   5,   8],
        [ 20,  50,  80],
        [200, 600, 800]])
tensor([[  4,   5,   6],
        [ 40,  50,  60],
        [500, 600, 700]])


In [10]:
tensor = torch.tensor(
    [
        [
            [
                [1,2,3],
                [4,5,6]
            ],[
                [10,20,30],
                [40,50,60]
            ]
        ]
    ]

)
tensor.shape
print(tensor.size())
print(tensor[0])
print(tensor[0,:,:,2])
tensor[0][0].ndim

torch.Size([1, 2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[10, 20, 30],
         [40, 50, 60]]])
tensor([[ 3,  6],
        [30, 60]])


2

In [9]:
tensor_org = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
tensor_reshaped = tensor_org.reshape(shape=(2,6))
tensor_reshape_1 = tensor_org.reshape(shape=(6,2))
tensor_reshape_2 = tensor_org.reshape(shape=(3,4))
print(tensor_reshaped)
print(tensor_reshape_1)
print(tensor_reshape_2)
print(tensor_reshaped.ndim ,tensor_reshape_1.ndim,tensor_reshape_2.ndim)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
2 2 2
