<a href="https://colab.research.google.com/github/Coder1010ayush/MachineLearning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) # __version__ is a dunder method in python oop.


2.0.1+cu118


In [7]:
# Scalar
scalar = torch.tensor(7) # constant values are also known as scalar
scalar
scalar.ndim # it gives dimension of tensor
scalar.item()


7

In [12]:
# Vector
vector = torch.tensor([3,4])
vector
vector.ndim  # it gives dimension of tensor
vector.shape # number of items in every row

torch.Size([2])

In [15]:
matrix = torch.tensor([[7,8],
                       [5,6]])
matrix
matrix.shape # number of items in every row
matrix.ndim # dimension of tensor

2

In [64]:
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor.ndim
tensor.shape
tensor
tensor[0]
tensor[0][0]
tensor[0][1]
tensor[0][2][0]

tensor(7)

### Random Tensors


In [ ]:
# random tensors
# forming random tensor in pytorch
random_tensor = torch.rand(3,4,2)
random_tensor.ndim
random_tensor.shape
random_tensor

In [ ]:
# image
image_tensor = torch.rand(size=(224,224,3))
image_tensor.shape
image_tensor.size()
image_tensor

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

In [ ]:
ones = torch.ones(size=(3,4),dtype=torch.int16)
ones
ones.dtype # data type of tensor elements

In [ ]:
# range tensor
range_tensor = torch.arange(0,10)
range_tensor
ten_zero = torch.zeros_like(input=range_tensor)
ten_one = torch.ones_like(input=range_tensor)
ten_zero
ten_one

### Tensor data type

In [ ]:
from pickle import FALSE
tensor = torch.tensor([3.0,4.2,5.6],
                      device=None,
                      requires_grad=True,
                      dtype=torch.float16)
integer_tensor = torch.tensor([1,2,3,4,5],
                              device=None,
                              requires_grad=False,
                              dtype =torch.int32)

tensor.dtype
integer_tensor
tensor_16_bit = tensor.type(torch.float16)
tensor_16_bit.dtype

In [69]:
# Information about tensor
some_tensor = torch.rand(3,4)
some_tensor
print("Shape of tensor is : ",some_tensor.shape)
print("Dimension of tensor is : ",some_tensor.ndim)
print("dtype of element : ",some_tensor.dtype)
print("Device info : ",some_tensor.device)

Shape of tensor is :  torch.Size([3, 4])
Dimension of tensor is :  2
dtype of element :  torch.float32
Device info :  cpu


In [73]:
# manipulating tensors
# operations : addition subtraction multiplication
first = torch.tensor(7)
second = torch.tensor(10)
first.mul(second)
first.add(second)
first.subtract(second)
first+20

tensor(27)

In [80]:
one = torch.tensor([1,2,3,4])
two = torch.tensor([6,7,8,9])
one.add(two)
one.mul(two)
one +10
two *2

# another way to do same thing in pytorch
torch.add(one,two)
torch.mul(one,two)

tensor([ 6, 14, 24, 36])

In [91]:
# Matrix multiplication
# 01 Scalar product
%%time
# this function give wall time
tensor_1 = torch.tensor([2,34,5,6])
print(tensor_1*5)
tensor_2 = torch.tensor([[2,3,4,5]])
tensor_3 = torch.tensor([[2,3],[4,5]])
print(tensor_2.mul(tensor_1))
print(tensor_1.mul(tensor_2))


tensor([ 10, 170,  25,  30])
tensor([[  4, 102,  20,  30]])
tensor([[  4, 102,  20,  30]])
CPU times: user 4.43 ms, sys: 0 ns, total: 4.43 ms
Wall time: 4.56 ms


In [101]:
# 02 Dot Product
%%time
tensor_f = torch.tensor([[2,3,4]])
print(tensor_f.shape)
tensor_s = torch.tensor([[2,3,5]])
print(tensor_s.shape)
tensor_t = torch.rand(size=(3,1))
tensor_f = torch.rand(size=(1,3))
print(tensor_f)
print(tensor_t)
print(torch.matmul(tensor_f,tensor_t))

torch.Size([1, 3])
torch.Size([1, 3])
tensor([[0.2530, 0.0944, 0.9952]])
tensor([[0.0820],
        [0.5453],
        [0.8569]])
tensor([[0.9250]])
CPU times: user 6.58 ms, sys: 0 ns, total: 6.58 ms
Wall time: 7.69 ms


In [108]:
# Finding the min , max and mean and sum or product

tensor_1 = torch.arange(0,100,10)
tensor_2 = torch.arange(0,200,10)
torch.min(tensor_1)
torch.max(tensor_2)
torch.mean(tensor_1.type(torch.float32))
torch.mean(tensor_2.type(torch.float32))


tensor(95.)

In [111]:
# tensor aggregation
# finding positional min and max

tensor_1 = torch.arange(0,100,10)
tensor_2 = torch.arange(0,200,10)
tensor_1.argmin()
tensor_2.argmin()
tensor_1.argmax()
tensor_2.argmax()

tensor(19)

In [126]:
# Reshaping Squeezing Unsqueezing
# reshape : a reshape an input tensor to a defined shape
# view : same as reshape but shares same memory as original
# stacking : concatenate to each other by side by side or top of each other
# squeezing : remove all 1 dimensions from a tensor
# Unsqueez : add one dimension to tensor
# permute : return a view of input with dimensions permuted in a certain way
x = torch.arange(0,10)
x.shape
x_reshaped = x.reshape(10,1)
x,x_reshaped

x_view = x.view(2,5)
x_view

x_stack = torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])